baseurl = "http://steeltoe-stage.cfapps.io"
languageCode = "en-us"
title = "Steel Toe"

[params]
    description = "Cloud Native .NET Applications - Harnessing the Power of Spring Cloud and Cloud Foundry"
    author_url = "http://pivotal.io"
    project_url = "http://github.com/SteelToeOSS"
    project_documentation = "/docs"
    github_project_name = "Samples"
    github_user_name = "SteelToeOSS"

    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"
